version: '3.8'

services:
  jasperreports:
    image: jasperserver-image
    ports:
      - '8080:8080'
      - '8443:8443'
    depends_on:
      - postgresql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - JASPERREPORTS_DATABASE_HOST=postgresql
      - JASPERREPORTS_DATABASE_PORT_NUMBER=3306
      - JASPERREPORTS_DATABASE_NAME=jasperserver_db
      - JASPERREPORTS_DATABASE_USER=root
      - JASPERREPORTS_DATABASE_PASSWORD=1234
    networks:
      - jasper_network

  postgresql:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - POSTGRES_ALLOW_EMPTY_PASSWORD=yes
      - POSTGRES_ROOT_PASSWORD=1234  # Change this to your actual root password
      - POSTGRES_DATABASE=jasperserver_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - jasper_network
    expose:
    - '5432'

networks:
  jasper_network:
    driver: bridge
 