name: JasperReports Docker Image CI/CD

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get the number of commits
        id: get_commit_count
        run: echo "COMMIT_COUNT=$(git rev-list --count HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          IMAGE_VERSION=v0.1.1
          docker build -t jasper_image:$IMAGE_VERSION .

      - name: Push Docker image with 'latest' tag
        run: |
          IMAGE_VERSION=v0.1.1
          docker tag jasper_image:$IMAGE_VERSION ghcr.io/acolita/jasperreports-server-docker-container:latest
          docker push ghcr.io/acolita/jasperreports-server-docker-container:latest
