name: JasperReports Docker Image CI/CD

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Read version from file
        id: read_version
        run: |
          VERSION=$(cat VERSION)
          echo "IMAGE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t jasper_image:${{ env.IMAGE_VERSION }} .

      - name: Push Docker image to GitHub Packages
        run: |
          docker tag jasper_image:${{ env.IMAGE_VERSION }} ghcr.io/acolita/jasperreports-server-docker-container:${{ env.IMAGE_VERSION }}
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/acolita/jasperreports-server-docker-container:${{ env.IMAGE_VERSION }}

      - name: Push Docker image with 'latest' tag
        run: |
          docker tag jasper_image:${{ env.IMAGE_VERSION }} ghcr.io/acolita/jasperreports-server-docker-container:latest
          docker push ghcr.io/acolita/jasperreports-server-docker-container:latest
