name: JasperReports Docker Image CI/CD

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t JasperReports_DockerImage .

      - name: Push Docker image to GitHub Packages
        run: |
          docker tag ${{ secrets.GITHUB_REPOSITORY }} ghcr.io/${{ secrets.GITHUB_REPOSITORY }}:latest
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ secrets.GITHUB_REPOSITORY }}:latest