name: JasperReports Docker Image CI/CD

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          IMAGE_VERSION=${{ VERSION }}
          docker build -t jasper_image:$IMAGE_VERSION .

      - name: Push Docker image to GitHub Packages
        run: |
          IMAGE_VERSION=${{ VERSION }}
          docker tag jasper_image:$IMAGE_VERSION ghcr.io/acolita/jasperreports-server-docker-container:$IMAGE_VERSION
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/acolita/jasperreports-server-docker-container:$IMAGE_VERSION

      - name: Push Docker image with 'latest' tag
        run: |
          docker tag jasper_image:$IMAGE_VERSION ghcr.io/acolita/jasperreports-server-docker-container:latest
          docker push ghcr.io/acolita/jasperreports-server-docker-container:latest
